documentation:
- changed-files:
  - any-glob-to-any-file:
    - "doc/source/*"
    - "README.md"

maintenance:
- changed-files:
  - any-glob-to-any-file:
    - ".github/**/*"
    - "pyproject.toml"

testing:
- changed-files:
  - any-glob-to-any-file:
    - "tests/**/*"
